name: Multijob workflow to build and deploy Docker app to Azure

on: push

jobs:   
  deploy-using-azure-pipelines:
    runs-on: ubuntu-latest
    steps:
      - run: |
         response_code=$(curl -s -o /dev/null -w "%{http_code}" --location 'https://dev.azure.com/agilops/bicep/_apis/build/builds?api-version=6.0' --header 'Content-Type: application/json' --header 'Authorization: Basic ${{ secrets.AZURE_DEVOPS_TOKE }}' --data '{"definition": {"id": "6"},"sourceBranch": "refs/heads/develop"}')
         if [[ $response_code -eq 200 ]]; then
           echo "Request successful"
         else
           echo "Request failed with response code $response_code"
           exit 1
         fi    
    #- name: 'Trigger an Azure Pipeline to deploy the app to PRODUCTION'
      #uses: Azure/pipelines@releases/v1
      #with:
        #azure-devops-project-url: 'https://dev.azure.com/agilops/bicep'
        #azure-pipeline-name: 'bicep' 
        #azure-devops-token: '${{ secrets.AZURE_DEVOPS_TOKEN }}'
