name: Multijob workflow to build and deploy Docker app to Azure

on: push

jobs:   
  deploy-using-azure-pipelines:
    runs-on: ubuntu-latest
    steps:
    - name: 'Trigger an Azure Pipeline to deploy the app to PRODUCTION'
      uses: Azure/pipelines@releases/v1
      with:
        azure-devops-project-url: 'https://dev.azure.com/agilops/bicep'
        azure-pipeline-name: 'bicep' 
        azure-devops-token: '${{ secrets.AZURE_DEVOPS_TOKEN }}'
